### ISSUE TITLE
Broken with zircote/swagger-php v2.0.11

### ISSUE THREAD

**Issue by ndurchx** [lichunqiang/yii2-swagger#10]
Since the update of zircote/swagger-php to 2.0.11, this package is broken.
The definitions can´t be found.

**Comment by lichunqiang** [comment]
hi @ndurchx  Can provide more information about this?

I had try with [demo project](https://github.com/lichunqiang/yii2-swagger-demo), it works fine.

**Comment by ndurchx** [comment]
I could rebuild the issue also on the demo project.
The problem are subpaths. 

`500 : {"name":"PHP User Notice","message":"$ref \"#/definitions/request/\" not found for @SWG\\Schema() in \\app\\modules\\v1\\controllers\\UserController->actionQuery()`

- Two changes to rebuild:
/modules/v1/controllers/UserController.php:179
`     *      @SWG\Schema(ref = "#/definitions/request/UserIdList")`

- modules/v1/swagger/definitions.php:39
` * @SWG\Definition(required={"access_token", "username"}, @SWG\Xml(name="UserIdList"), definition="request/UserIdList")`

This works on 2.0.10

**Comment by lichunqiang** [comment]
hi . @ndurchx  

I found that the changelog `Added validation of internal refs`, maybe is invalid on the old version but no validation.

You should change this behavior.

Let's have a future discussion if you have any question.

**Comment by ndurchx** [comment]
https://github.com/zircote/swagger-php/issues/435
Possibly solving at swagger-php
