### ISSUE TITLE
Create branch for 3.x

### ISSUE THREAD

**Issue by McSneaky** [lichunqiang/yii2-swagger#13]
Can you please make branch for 3.x so I can make PR to there?

**Comment by lichunqiang** [comment]
Sorry for late response.

You can work for it, i will make the change for your PR.

**Comment by McSneaky** [comment]
Waiting for zircote/swagger-php fix https://github.com/zircote/swagger-php/pull/472

**Comment by mikk150** [comment]
@McSneaky RequestBody is now supported in swagger-php

**Comment by ddanielroche** [comment]
I want to try swagger-php 3.x-dev. Should I fork or can we make a branch for this version?

**Comment by bloodf** [comment]
The V3 will be a good improvment.

**Comment by ddanielroche** [comment]
In my personal branch I have swagger ui 3.x. I would like to integrate it into this repository. I also added support for the urls property.

**Comment by McSneaky** [comment]
You can make PR to here :slightly_smiling_face:

**Comment by ddanielroche** [comment]
Add PR #16 for this solution

**Comment by lichunqiang** [comment]
Try: 2.0.0-alpha
