### ISSUE TITLE
Install config

### ISSUE THREAD

**Issue by CtrlShiftN** [lichunqiang/yii2-swagger#20]
Please specify the installation guide. 
About create controller, Models, bla bla... from the beginning and more specific!
I am a newbie for this field so I do not know how to config to use it!
Sth like:
`/**
 * Class Module Api
 *
 *
 * @SWG\Swagger(
 *     basePath="{{basePath}}",
 *     host="{{host}}",
 *     schemes={"http"},
 *     @SWG\Info(
 *         version="1.0",
 *         title="Example API",
 *         @SWG\Contact(name="Example", url="http://example.ru"),
 *     ),
 *     @SWG\Definition(
 *         definition="Error",
 *         required={"code", "message"},
 *         @SWG\Property(
 *             property="code",
 *             type="integer",
 *             format="int32"
 *         ),
 *         @SWG\Property(
 *             property="message",
 *             type="string"
 *         )
 *     )
 * )
 */`

**Comment by lichunqiang** [comment]
https://github.com/lichunqiang/yii2-swagger-demo

It maybe help u
