### ISSUE TITLE
Support "bower-asset/swagger-ui": "^4.1"?

### ISSUE THREAD

**Issue by developedsoftware** [lichunqiang/yii2-swagger#30]
Seems to work just fine, but just wondered if anything needed changing to work with 4.1 and above

**Comment by Krakozaber** [comment]
Updated the package versions, but the tag is needed.

**Comment by developedsoftware** [comment]
When can that be created ?

**Comment by Krakozaber** [comment]
@laxity7 tag it pliz

**Comment by laxity7** [comment]
@Krakozaber Maybe you wanted to mark @lichunqiang?
I don't have access

**Comment by Krakozaber** [comment]
@lichunqiang tag it pliz

**Comment by lichunqiang** [comment]
done
