### ISSUE TITLE
Add in header basic auth.

### ISSUE THREAD

**Issue by ihippik** [lichunqiang/yii2-swagger#4]
```
  function addAuthorization() {
    var username = encodeURIComponent($('#input_username').val());
    var password = encodeURIComponent($('#input_password').val());
    if (username && username.trim() != "" && password && password.trim() != "") {
      var basicAuth = new SwaggerClient.PasswordAuthorization('basic', username, password);
      window.swaggerUi.api.clientAuthorizations.add("basicAuth", basicAuth);
    }
  }
  $('#input_username').change(addAuthorization);
  $('#input_password').change(addAuthorization);
```

**Comment by lichunqiang** [comment]
hi @ihippik what's your purpose?can you explain? thanks.

you want to have an enhancement, PR is welcome.

**Comment by ihippik** [comment]
Without this function, and two fields for name and password, I could not add headers basic auth.
Although I had in my json:
                "security": [
                    {
                        "basicAuth": []
                    }
                ]
...
    "securityDefinitions": {
        "basicAuth": {
            "type": "basic",
            "description": "HTTP Basic Authentication. Works over `HTTP` and `HTTPS`"
        }
    },
...
but I can not add these headers in the UI.

**Comment by lichunqiang** [comment]
ok, PR is welcome.

**Comment by lichunqiang** [comment]
Hi, this resolve in new version. You can have a try.
