### ISSUE TITLE
The package is not available in a stable-enough version according to your minimum-stability setting

### ISSUE THREAD

**Issue by urfusion** [lichunqiang/yii2-swagger#5]
I am getting below error even I have updated my composer

The package is not available in a stable-enough version according to your minimum-stability setting

composer

    "minimum-stability": "dev"

**Comment by urfusion** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/8436372/23498531/169f2c24-ff4e-11e6-84fc-13b068761cd0.png)

**Comment by lichunqiang** [comment]
Can i get you `fxp/composer-asset-plugin` version? Is over `v1.2.2`?

You can refer the demo project: https://github.com/lichunqiang/yii2-swagger-demo/blob/master/composer.json#L26

either `minimum-stability` use `stable` for `light/yii2-swagger=~1.0.4` or  `dev` for `light/yii2-swagger=*@dev` is passed

**Comment by Slauta** [comment]
@urfusion Hi,
I solved this problem.
Install fxp/composer-asset-plugin: `php composer.phar require fxp/composer-asset-plugin --dev`

**Comment by urfusion** [comment]
- light/yii2-swagger 1.0.4 requires bower-asset/swagger-ui 2.2.10 -> no matc
hing package found.

**Comment by lichunqiang** [comment]
@urfusion u can try the demo project. It works fine and no your mentioned issue..

**Comment by urfusion** [comment]
I am trying the demo. 
but getting error

> http://localhost/yii2-swagger-demo-master/v1/users?access_token=Bearer%204p9mj82PTl1BWSya7bfpU_Nm8u07hkcB

I have installed it in a folder inside htdocs

**Comment by lichunqiang** [comment]
@urfusion  you can just run ``yii serve` to start a internal server.
BTW, what's the error?

**Comment by urfusion** [comment]
![screenshot_12](https://cloud.githubusercontent.com/assets/8436372/23671743/524263a2-0392-11e7-8338-d1d49dd6bd62.png)

**Comment by urfusion** [comment]
Is there any other way to run. Because when I built front end and backend with it its not possible to run `yii server` each time.

**Comment by lichunqiang** [comment]
You should configure `web` directory as http server's root path.

As apache:

```
<VirtualHost *:80>
	ServerName www.mysite.com
	DocumentRoot d:/wamp/www/demo/frontend/web
</VirtualHost>
```
then modify the windows `host` file, configure `www.mysite.com 127.0.0.1` for example. Finally, you can asscess `www.mysite.com` to view the project.

**Comment by urfusion** [comment]
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://www.swagger.local/site/api"}]}

**Comment by lichunqiang** [comment]
@urfusion You should ingore this. This behaivor is to valid your schema from remote, but the project is deployed locally, so the swagger remote check server can not access to it.
