### ISSUE TITLE
v1.0.3 Update not working

### ISSUE THREAD

**Issue by letsVerifyAscendro** [lichunqiang/yii2-swagger#6]
Hi, 
After today update the extension stop working.

We have some js errors as:

"NetworkError: 404 Not Found - /assets/80322b46/lib/underscore-min.js"
"NetworkError: 404 Not Found - /assets/80322b46/lib/highlight.7.3.pack.js"
"NetworkError: 404 Not Found - /assets/80322b46/lib/handlebars-2.0.0.js"

ReferenceError: SwaggerUi is not defined

Thanks

**Comment by lichunqiang** [comment]
Sorry for that. pls try 1.0.4.
