### ISSUE TITLE
api_key 在nginx下通过header发送，无法验证。

### ISSUE THREAD

**Issue by brucebnu** [lichunqiang/yii2-swagger#7]
新版本的swagger ui 不在使用get验证登录，改用header。apache下正常。
nginx下自定义header，
在nginx.conf 开启
underscores_in_headers on;  #默认off
api_key会解析为api-key，php无法获取进行验证，报错如下，建议统一api-key

{"securityDefinitions":{"api_key":{"in":"header","type":"apiKey","name":"api_key"}},"swagger":"2.0","schemes":["http"],"info":{"title":"Please take authentication firstly."}}

参考：http://stackoverflow.com/questions/22856136/why-underscores-are-forbidden-in-http-header-names

**Comment by lichunqiang** [comment]
你可以先通过配置`SwaggerApiAction::apiKeyParam`改成 `api-key`来试试。

**Comment by brucebnu** [comment]
是的，现在是这么处理的，谢谢！
