### ISSUE TITLE
composer 安装报错

### ISSUE THREAD

**Issue by Aibric** [lichunqiang/yii2-swagger#9]
1、composer require --prefer-dist light/yii2-swagger "~1.0.4" --dev

error 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - light/yii2-swagger 1.0.5 requires bower-asset/swagger-ui 2.2.10 -> no matching package found.
    - light/yii2-swagger 1.0.4 requires bower-asset/swagger-ui 2.2.10 -> no matching package found.
    - Installation request for light/yii2-swagger ~1.0.4 -> satisfiable by light/yii2-swagger[1.0.4, 1.0.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

2、composer require --prefer-dist light/yii2-swagger "~1.0.5" --dev

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for light/yii2-swagger ~1.0.5 -> satisfiable by light/yii2-swagger[1.0.5].
    - light/yii2-swagger 1.0.5 requires bower-asset/swagger-ui 2.2.10 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by lichunqiang** [comment]
fxp-asset 的版本是多少

**Comment by Aibric** [comment]
windows composer version 1.4.1，我没有安装了。fxp/composer-asset-plugin插件。。。

**Comment by lichunqiang** [comment]
用yii不装这个插件，你是怎么做到的额。。

**Comment by Aibric** [comment]
我是在官方网站直接下载的源码啊。。。

**Comment by lichunqiang** [comment]
这个，你如果用composer安装的话，得按照yii文档来，先全局装上那个插件才行。。

**Comment by Aibric** [comment]
好的，那我在安装一下fxp/composer-asset-plugin 插件吧。

**Comment by Aibric** [comment]
@lichunqiang  谢谢，安装 完 fxp/composer-asset-plugin OK了。
